name: Cypress Tests

on: [push]

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.13.1-chrome-125.0.6422.60-1-ff-126.0-edge-125.0.2535.51-1
      options: --user 1001
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
      
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:8081
          wait-on-timeout: 60
          browser: chrome
          spec: cypress/e2e/isolation/**
          command-prefix: 'percy exec -- npx'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

  cypress-run-firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.13.1-chrome-125.0.6422.60-1-ff-126.0-edge-125.0.2535.51-1
      options: --user 1001
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
      
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:8081
          wait-on-timeout: 60
          browser: firefox
          spec: cypress/e2e/isolation/**

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
          
  cypress-run-edge:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.13.1-chrome-125.0.6422.60-1-ff-126.0-edge-125.0.2535.51-1
      options: --user 1001
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
      
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:8081
          wait-on-timeout: 60
          browser: edge
          spec: cypress/e2e/isolation/**

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore